stages:
  load_data:
    cmd: python simplemlapp-with-ci-dvc/load_data.py --config=params.yaml
    deps:
    - simplemlapp-with-ci-dvc/get_data.py
    - simplemlapp-with-ci-dvc/load_data.py
    - data_given/winequality.csv
    outs:
    - data/raw/winequality.csv
  
  split_data:
    cmd: python simplemlapp-with-ci-dvc/split_data.py --config=params.yaml
    deps:
    - simplemlapp-with-ci-dvc/split_data.py
    - data/raw/winequality.csv
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv 

  train_and_evaluate:
    cmd: python simplemlapp-with-ci-dvc/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv 
    - simplemlapp-with-ci-dvc/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib